# R for travis documentation: https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r: bioc-devel
bioc_check: true

# Strict checks in place
warnings_are_errors: false

branches:
  only:
    - RELEASE_3_11

# Test code coverage
r_github_packages:
  - jimhester/covr
  - Bioconductor/AnVIL

script:
  - |
    R CMD build .
    travis_wait 30 R CMD check cBioPortalData*tar.gz

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
  slack:
    secure: bjJIMud5gc68qMSI4DHEKqeh9Z7ceeS9Q/dnV7eJh2yyWQ2UlwwVSpftoqPPnrddOuEkbwjrsj/QHHd0AI0kQSuJK6LlshWLXlG75q6+O/97yKmpVPSvh0YsqsDCXven9xxT0F4+UUpf8bwC2pzN8jwrkWXa7i96ISjvyc/uBrIqSltmOlBjRWeBdHUMNds9LuotOEdDP7OVy11rQIXzRf5wstxG7M/4At2D5i+wOF83Y+8W9m8QkK68LMqNt4f7U3QmRLkc58h1Xprwe+eCefY8Rc4zGKjyciBKxIp6qYexUR4IVvuWv33DyjS1RgmqWRKYQueYv+oGFhlZUNZTqbFlCk0cxF4S2wS+uKB7lbalysbxIfc8e5bbQqBFNA+48O8BGCR0j3t8Qsbt+huJU1MAqszH5jqNZP3ERNobB2Bgh6kUzSLL2lLvzj+2mBojScG4JvS5Qf8CmlS67gNeiOoYgYLDXOS6PBF1AyFFBQhlS4rHuHGnmEIysBZxE9L5v2CVtqggLH6buitqRzdlltnM6v0E0J+v6dRynB//P29Zzg3F75OfEb/+JlXwAFdjXyABbgg8y1GfdoHi9Gaf3lfiSb4/YULo/RtxXdTEB+Xsn7hdjXNjhxbDK//MeCbxlib7koSzssyQDM+bH+C1e6nqCCr5SbS9EaVJ/pb4Aow=

