name: cBioRel

on: push

jobs:
  checkRelease:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ runner.os }}-r-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-1-

      - name: Install Package Dependencies
        run: |
          Rscript -e "BiocManager::install(c('remotes', 'rcmdcheck', 'covr', 'pkgdown', 'AnVIL'), ask = FALSE, update = TRUE)"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: System dependencies
        run: |
          pip install ghp-import

      - name: Check Package
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual'), error_on = 'error', check_dir = 'check')"

      - name: Build pkgdown
        run: |
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_site(".")'

      - name: Install deploy dependencies
        run: |
          apt-get update
          apt-get -y install rsync

      - name: Deploy to GH Pages ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.5.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
